### ISSUE TITLE
New security vulnerability discovered in dependency: hoek <5.0.3

### ISSUE THREAD

**Issue by intribeco** [InTribe/errlog.io-webhook#2]
>  | InTribe/errlog.io-webhook
> 
> -- | --
> Known moderate severity security vulnerability detected in hoek < 5.0.3 defined in package-lock.json.package-lock.json update suggested: hoek ~> 5.0.3.Always verify the validity and compatibility of suggestions with your codebase. | Known moderate severity security vulnerability detected in hoek < 5.0.3 defined in package-lock.json. | package-lock.json update suggested: hoek ~> 5.0.3. | Always verify the validity and compatibility of suggestions with your codebase.
> Known moderate severity security vulnerability detected in hoek < 5.0.3 defined in package-lock.json.
> package-lock.json update suggested: hoek ~> 5.0.3.
> Always verify the validity and compatibility of suggestions with your codebase.

**Comment by AlbertHambardzumyan** [comment]
PR #3 
[Issue](https://intribe.atlassian.net/browse/IMVP-316)

As we all know, the problem is in `hoek` module and in our case, it goes to `request` module, which uses `hoek` internaly.

NVD refers to this as MAID vulnerability and states that hoek node module before 5.0.3 suffers from it [See](https://nvd.nist.gov/vuln/detail/CVE-2018-3728#vulnCurrentDescriptionTitle)

On the other hand, Snyk states <4.2.1 || >=5.0.0 <5.0.3 [See](https://snyk.io/vuln/npm:hoek:20180212)

[Fix in 5.0.3](https://github.com/hapijs/hoek/commit/32ed5c9413321fbc37da5ca81a7cbab693786dee)

Fix has been backported to 4.x track of the module and published as 4.2.1. [See](https://intribe.atlassian.net/browse/IMVP-316#231)
[Fix in 4.2.1](https://github.com/hapijs/hoek/commit/5aed1a8c4a3d55722d1c799f2368857bf418d6df)

It appears that the CVE is incorrectly considering hoek v4.2.1 as vulnerable and may be why so many github repos are now reporting a vulnerability.

We use request ^2.83.0 and hoek locked on 4.2.0
I have upgraded to 2.85.0 and hoek locked on 4.2.1 (contains fix for the bug)

However, git might consider it vulnarable until CVE response.
